---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1
  - name: ubuntu-14.04

suites:
  - name: agent
    run_list:
      - recipe[dkron-test::agent]
    attributes:
  - name: server
    run_list:
      - recipe[dkron-test::server]
    