---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.3
  - name: ubuntu-16.04

suites:
  - name: agent
    run_list:
      - recipe[dkron-test::agent]
    attributes:
  - name: server
    run_list:
      - recipe[dkron-test::server]
